title: TDD - Infografía
description: Infografía sobre TDD
sitename: TDD - Infografía
baseurl: '/tdd-infographic'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
author: Marvin López
author_url: https://about.me/marvlm